### ISSUE TITLE
Users can't change password with Heroku

### ISSUE THREAD

**Issue by alahab2** [TechLadies/highpoint#93]
![screen shot 2016-11-15 at 2 24 00 pm](https://cloud.githubusercontent.com/assets/19661205/20295326/3db57fb0-ab3f-11e6-86dd-1578ddf41b77.png)

After "Submit" button is pressed, the app crashes. 
@Drenmi could you please check the logs?

**Comment by Drenmi** [comment]
```
Completed 500 Internal Server Error in 384ms (ActiveRecord: 11.8ms)

Net::SMTPAuthenticationError (535 Authentication failed: The provided authorization grant is invalid, expired, or revoked

app/controllers/clearance/passwords_controller.rb:68:in `deliver_email'
app/controllers/clearance/passwords_controller.rb:26:in `create'
```

**Comment by alahab2** [comment]
Thanks!

**Comment by Drenmi** [comment]
Not sure why this is happening. :-(

**Comment by alahab2** [comment]
Still not working 😢 
@Drenmi logs? 🙏
